
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CBRA = 9;
  public static final int AFFECT = 11;
  public static final int OACC = 5;
  public static final int PLUS = 14;
  public static final int CACC = 6;
  public static final int OPAR = 12;
  public static final int CAT = 10;
  public static final int COMMA = 7;
  public static final int ident = 2;
  public static final int EOF = 0;
  public static final int MULT = 15;
  public static final int CPAR = 13;
  public static final int t_ident = 3;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int integer = 4;
  public static final int NEWL = 16;
  public static final int OBRA = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ident",
  "t_ident",
  "integer",
  "OACC",
  "CACC",
  "COMMA",
  "OBRA",
  "CBRA",
  "CAT",
  "AFFECT",
  "OPAR",
  "CPAR",
  "PLUS",
  "MULT",
  "NEWL",
  "PRINT"
  };
}

